//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by w32los.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_DEFAULT_FONT                129
#define IDD_OPTIONS                     139
#define IDD_LANGPACK                    140
#define IDD_ORGANIZE                    141
#define IDD_DOWNLOAD                    142
#define IDD_USERPASS                    143
#define IDD_PROXY                       144
#define IDI_COMPUTER                    145
#define IDI_WWW                         146
#define IDD_LAYOUT                      147
#define IDD_SIGNATURE                   148
#define IDD_SIGNATURE_TEMPLATE          149
#define IDD_POST_PAIR                   151
#define IDI_POSTPAIR                    152
#define IDB_COPY                        153
#define IDB_PASTE                       154
#define IDB_FONTPROPERTIES              158
#define IDB_COPYPRESSED                 161
#define IDB_PASTEPRESSED                162
#define IDB_FONTPROPERTIESPRESSED       163
#define IDB_PASTEINSENSITIVE            164
#define IDC_STATIC_W32LOS_VER           1000
#define IDC_DLGLANGLIST                 1001
#define IDC_MAINBAR_LANGBOX             1004
#define IDC_MAINBAR_LANGBOX2            1005
#define IDC_START_ONCE                  1006
#define IDC_MAINBAR_DATETIME            1007
#define IDC_USEUSP10                    1008
#define IDC_YEAR1                       1009
#define IDC_YEAR2                       1010
#define IDC_WRITELOGFILE                1011
#define IDC_CURRDOCLANG                 1012
#define IDC_UNPACK                      1013
#define IDC_PROXY                       1014
#define IDC_LISTINSTALLED               1015
#define IDC_DELETE                      1016
#define IDC_YEARCOMBO                   1017
#define IDC_DOWNLOAD                    1018
#define IDC_DOWNLOAD_PROGRESS           1019
#define IDC_STATIC_TEXT_YEAR            1020
#define IDC_USERNAME                    1021
#define IDC_PASSWORD                    1022
#define IDC_POST_PAIR_PROXY             1023
#define IDC_RESET                       1024
#define IDC_DOWNLOAD_SELECT_ALL         1025
#define IDC_SWAP                        1026
#define IDC_DOWNLOAD_SELECT_MISSING     1027
#define IDC_INSERT_PAROL1               1028
#define IDC_INSERT_PAROL2               1029
#define IDC_PROXY_PRECONFIG             1033
#define IDC_PROXY_DIRECT                1034
#define IDC_PROXY_MANUAL                1035
#define IDC_YEAR_HINT                   1036
#define IDC_LANGPACK_PROXY              1037
#define IDC_ORGANIZE_PROXY              1038
#define IDC_ORGANIZE_VIEW               1039
#define IDC_SIGNATURE_ON                1040
#define IDC_SIGNATURE_TARGET            1041
#define IDC_SIGNATURE_TARGET_SELECT     1042
#define IDC_SIGNATURE_CURRENT           1043
#define IDC_EDIT_SIGNATURE_TEMPLATE     1044
#define IDC_WRITE_SIGNATURE             1045
#define IDC_SIGNATURE_PREVIEW           1046
#define IDC_SIGNATURE_TEMPLATE_TEXT     1047
#define IDC_SIGNATURE_KEYWORDS          1048
#define IDC_INSERT_SIGNATURE_KEYWORD    1049
#define IDC_SIGNATURE_DLG_TEMPLATE      1050
#define IDC_UPDATE_SIGNATURE            1051
#define IDC_SIGNATURE_TEMPLATE_HELP     1054
#define IDC_AUTOLANGPACK                1055
#define IDC_VIEWLOGFILE                 1056
#define IDC_SIGNATURE_UTF8              1057
#define IDC_INFO                        1058
#define IDC_PAROL1                      1059
#define IDC_PAROL2                      1060
#define IDC_CONTEXT_PAROL1              1061
#define IDC_CONTEXT_PAROL2              1062
#define IDC_BIBLEEDITION                1063
#define IDC_ORDER_THIS                  1064
#define IDC_ORDER_BOTH                  1065
#define IDC_ORDER_DONTKNOW              1066
#define IDC_TYPE_EXAMPLE                1067
#define IDC_TYPE_OPPOSITE               1068
#define IDC_TYPE_FULFILLMENT            1069
#define IDC_TYPE_EXPLANATION            1070
#define IDC_TYPE_EXTENSION              1071
#define IDC_TYPE_CITATION               1072
#define IDC_TYPE_PARALLEL               1073
#define IDC_TYPE_OTHER                  1074
#define IDC_TYPE_DONTKNOW               1075
#define IDC_TYPE_TEXT_OTHER             1076
#define IDC_SEND                        1077
#define IDC_THIRDPARTYFREE              1078
#define IDC_TL_FONT                     1079
#define IDC_IL_FONT                     1080
#define IDC_L_FONT                      1081
#define IDC_SL_FONT                     1082
#define IDC_TL_SIZE                     1084
#define IDC_IL_SIZE                     1085
#define IDC_L_SIZE                      1086
#define IDC_SL_SIZE                     1087
#define IDC_TL_PROPS                    1088
#define IDC_IL_PROPS                    1089
#define IDC_L_PROPS                     1090
#define IDC_SL_PROPS                    1091
#define IDC_TL_COPY                     1092
#define IDC_IL_COPY                     1093
#define IDC_L_COPY                      1094
#define IDC_SL_COPY                     1095
#define IDC_TL_PASTE                    1096
#define IDC_IL_PASTE                    1097
#define IDC_L_PASTE                     1098
#define IDC_SL_PASTE                    1099
#define IDC_LOSUNG_COPY                 1100
#define IDC_LOSUNG_PASTE                1101
#define IDC_LANGBIBLE_COMBO             1102
#define IDC_BKCOL_PROPS                 1103
#define IDC_LAYOUT_UNDO                 1104
#define IDC_LAYOUT_REDO                 1105
#define IDC_LAYOUT_ALL                  1106
#define IDS_INSTALL_TITLE               32781
#define IDS_INSTALL_STR                 32782
#define IDS_INSTALL_EXT                 32783
#define IDS_INSTALL_OK                  32784
#define IDS_FILEREAD_ERR                32785
#define IDS_FILEREADDAY_ERR             32786
#define IDS_CLIPBOARDERR                32787
#define IDS_USE_NEXT_YEAR               32790
#define IDS_WRITEERR                    32794
#define IDS_WRITEERR_1                  32795
#define IDS_LOZ_NOTLOZ                  32796
#define IDS_INSTALLED                   32798
#define IDS_INSTALLED_1                 32799
#define IDS_FILE_NOT_FOUND              32800
#define IDS_HELPFILE_PROGRAM            32807
#define IDS_LOADSHELL32_FAILED          32810
#define IDS_OPENFILE_FAILED             32811
#define IDS_GETSHELLEXECUTE_FAILED      32812
#define IDS_XLAT_USED                   32813
#define IDS_GET_VER_FAILED              32817
#define IDS_POSTPAIR_DATA_MISSING       32818
#define IDS_NO_FILE_TO_ACTIVATE         32819
#define IDS_REALLYDELETE                32820
#define IDS_DELETE_EACCES               32821
#define IDS_GETLIST_FAILED              32823
#define IDS_NOSESSION                   32824
#define IDS_INVALID_URL                 32825
#define IDS_INTERNET_ERROR              32826
#define IDS_GETFILE_FAILED              32827
#define IDS_FILENOTAVAIL                32828
#define IDS_URL_NOT_FOUND               32829
#define IDS_HTTP_STATUS                 32830
#define IDS_AUTHOR                      32831
#define IDS_SERVER_NOT_FOUND            32832
#define IDS_DOWNLOAD_TEXTS_YEAR         32833
#define IDS_GETTING_FILELIST            32834
#define IDS_GETTING_FILE                32835
#define IDS_INSTALLING_FILE             32836
#define IDS_FRAME_TITLE                 32837
#define IDS_POSTPAIR_FAILED             32838
#define IDS_POSTPAIR_OK                 32839
#define IDS_PLEASE_THIRDPARTYFREE       32840
#define ID_VIEW_DAYBACK                 33774
#define ID_VIEW_TODAY                   33775
#define ID_VIEW_MONTHNEXT               33777
#define ID_VIEW_MONTHPREVIOUS           33778
#define ID_VIEW_DAYFORTH                33780
#define ID_HELP_PROGRAM                 33806
#define ID_HELP_PROJECT                 33807
#define ID_FILE_STARTUPFLDR             33808
#define ID_EDIT_LAYOUT                  33812
#define ID_EDIT_OPTIONS                 33813
#define ID_EDIT_POST_PAIR               33814
#define ID_VIEW_XLAT                    33819
#define ID_COMBO_BUTTON                 33829
#define ID_DATETIME_BUTTON              33830
#define ID_FILE_ACTUALIZE               33832
#define ID_FILE_ORGANIZE                33833
#define ID_FILE_SIGNATURE               33836
#define IDS_SIGNATURE_TARGET_EMPTY      33837
#define IDS_SIGNATURE_TARGET_NOT_EXIST  33838
#define IDS_SIGNATURE_TARGET_SELECT_TITLE 33839
#define IDS_SIGNATURE_STR               33840
#define IDS_SIGNATURE_EXT               33841
#define IDS_SIGNATURE_TARGET_EMPTY_NOWRITE 33842
#define IDS_SIGNATURE_TEMPLATE_WRITE_FAILED 33843
#define IDS_SIGNATURE_TEMPLATE_EMPTY_NOWRITE 33844
#define IDS_SIGNATURE_TEMPLATE_KW_LOSUNG 33845
#define IDS_SIGNATURE_TEMPLATE_KW_TL    33846
#define IDS_SIGNATURE_TEMPLATE_KW_OT    33847
#define IDS_SIGNATURE_TEMPLATE_KW_NT    33848
#define ID_COMBO2_BUTTON                33849

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         33850
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
